
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    name: root
    password: root
  redis:
    port: 6379
    host: 192.168.1.114
    password: 123456
    database: 0
mybatis:
  mapper-locations: classpath:jie/a/mapper/*.xml
  type-aliases-package: jie.a.model